# To boot the app run the following:
# docker-compose run mic-io
# NOTE: Version 3.9 requires at least docker-compose version 1.29.0 !
version: "3.9"

services:
  mic-io:
    build: ./
    env_file:
      - .env
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]
