version: '3.9'

services:
  api: &main_app
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: sergeant:${SERGEANT_VERSION:-latest}
    restart: always
    env_file:
    - .env
    labels:
      # Enables traefik for this container.
    - traefik.enable=true
    - traefik.http.routers.sergeant.rule=Host(`${SERGEANT_TRAEFIK_HOST:-sergeant.localhost}`)
    - traefik.http.routers.sergeant.entrypoints=http
    - traefik.http.routers.sergeant.service=sergeant
    - traefik.http.services.sergeant.loadbalancer.server.port=${SERGEANT_PORT:-8000}
    networks:
    - default
    - traefik-shared
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rmq:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SERGEANT_HOST: 0.0.0.0
      SERGEANT_DB_HOST: sergeant-db
      SERGEANT_DB_PORT: 5432
      SERGEANT_DB_USER: sergeant
      SERGEANT_DB_PASS: sergeant
      SERGEANT_DB_BASE: sergeant
      SERGEANT_RABBIT_HOST: sergeant-rmq
      SERGEANT_REDIS_HOST: sergeant-redis
      TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS: '["sergeant-kafka:9092"]'

  taskiq-worker:
    <<: *main_app
    labels: []
    command:
    - taskiq
    - worker
    - sergeant.tkq:broker

  db:
    image: postgres:13.8-bullseye
    hostname: sergeant-db
    environment:
      POSTGRES_PASSWORD: "sergeant"
      POSTGRES_USER: "sergeant"
      POSTGRES_DB: "sergeant"
    volumes:
    - sergeant-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U sergeant
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: sergeant:${SERGEANT_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      SERGEANT_DB_HOST: sergeant-db
      SERGEANT_DB_PORT: 5432
      SERGEANT_DB_USER: sergeant
      SERGEANT_DB_PASS: sergeant
      SERGEANT_DB_BASE: sergeant
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "sergeant-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  rmq:
    image: rabbitmq:3.9.16-alpine
    hostname: "sergeant-rmq"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    healthcheck:
      test: rabbitmq-diagnostics check_running -q
      interval: 3s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "sergeant-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: "bitnami/kafka:3.2.0"
    hostname: "sergeant-kafka"
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://sergeant-kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "sergeant-zookeeper:2181"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_healthy



volumes:
  sergeant-db-data:
    name: sergeant-db-data

networks:
  # Network for traefik.
  traefik-shared:
    name: traefik-shared
